### ISSUE TITLE
More about sliders

### ISSUE THREAD

**Issue by jixunmoe** [nojhamster/osu-parser#1]
Is there a way to calculate the slider duration or the end time?

Thanks.

**Comment by nojhamster** [comment]
Hi !
Yes it's possible, I guess I should add an **endTime** property to sliders, just like spinners. It's just a little more annoying because you need the current bpm and velocity :)

Meanwhile, here's the formula :

``` javascript
// First we get the slider velocity in osu!pixels per beat
// The SliderMultiplier is in hundreds of px per beat
var pxPerBeat = sliderMultiplier * 100 * currentSection.velocity

// With this we can get the slider length in beats
var slider.beatsNumber = (slider.pixelLength * slider.repeatCount) / pxPerBeat

// Then we multiply this with the beatLength (ms per beat) of the current timing section
var slider.msLength = slider.beatsNumber * currentSection.beatLength
```

I hope that's clear :)

**Comment by jixunmoe** [comment]
Great! Thank you so much!!

I tried to do it my self and failed.. Thanks!!

**Comment by Modricagon** [comment]
I made an equation. b = BPM, L = sliderlength, v = slider velocity, to calculate the duration of a slider in milliseconds

t (ms) = 600L/bv

For example:

b = 180
L = 550
v = 1.4

(600 * 550)/(180 * 1.4) = 1309.52380952ms
