### ISSUE TITLE
can't parse loved map

### ISSUE THREAD

**Issue by cyperdark** [nojhamster/osu-parser#4]
https://osu.ppy.sh/beatmapsets/575788#osu/1746492

**Comment by cyperdark** [comment]
i checked via console.log where he stopped and i got it there
![image](https://user-images.githubusercontent.com/21735205/89977044-b24fdd80-dc59-11ea-8f9e-03f37c42fc65.png)

**Comment by cyperdark** [comment]
i think it's because this slider
![screenshot9274](https://user-images.githubusercontent.com/21735205/89977186-09ee4900-dc5a-11ea-96c5-44b8b97a3388.jpg)

**Comment by cyperdark** [comment]
![image](https://user-images.githubusercontent.com/21735205/89977311-5afe3d00-dc5a-11ea-99ff-cc6f2fbd753f.png)

**Comment by cyperdark** [comment]
this one too https://osu.ppy.sh/beatmapsets/930865#osu/1943817

**Comment by cyperdark** [comment]
https://osu.ppy.sh/beatmapsets/1129044#osu/2358718
https://osu.ppy.sh/beatmapsets/933630#osu/1949106

**Comment by cyperdark** [comment]
?

**Comment by AuracleTech** [comment]
Parser is abandoned it looks like
I was about to report another issue 
![image](https://user-images.githubusercontent.com/40531871/220274691-5c7f7aeb-9ec9-40f0-8e94-d7e4251fdfc6.png)
![image](https://user-images.githubusercontent.com/40531871/220274742-f0719b9a-2433-41ed-9bab-ff8e3f1c0a02.png)
guess ill have to make my own parser
